export const Refers = {
    "Aaya" : {
        1: ["Dwaja", 1],
        2: ["Dumra", 0],
        3: ["Simha", 1],
        4: ["Shvana", 0],
        5: ["Vrushabha", 1],
        6: ["Khara", 0],
        7: ["Gaja", 1],
        8: ["Kaaka", 0],        
    },
    "Thithi": {
        1: ["Shu.Padya", 0],
        2: ["Shu.Bidige", 1],
        3: ["Shu.Tadige", 1],
        4: ["Shu.Chouti", 0],
        5: ["Shu.Panchami", 1],
        6: ["Shu.Shasti", 1],
        7: ["Shu.Saptami", 1],
        8: ["Shu.Astami", 0],
        9: ["Shu.Navami", 0],
        10: ["Shu.Dashami", 1],
        11: ["Shu.Ekadashi", 1],
        12: ["Shu.Dwadashi", 1],
        13: ["Shu.Trayodashi", 1],
        14: ["Shu.Chaturdashi", 0],
        15: ["Pournima", 0],
        16: ["Ba. Padya", 0],
        17: ["Ba. Bidige", 1],
        18: ["Ba. Tadige", 1],
        19: ["Ba. Chouti", 0],
        20: ["Ba. Panchami", 1],
        21: ["Ba. Shasti", 1],
        22: ["Ba. Saptami", 1],
        23: ["Ba. Astami", 0],
        24: ["Ba. Navami", 0],
        25: ["Ba. Dashami", 1],
        26: ["Ba. Ekadashi", 1],
        27: ["Ba. Dwadashi", 1],
        28: ["Ba. Trayodashi", 1],
        29: ["Ba. Chaturdashi", 0],
        30: ["Amavasya", 0],
    },
    "Vaara": {
        1: ["Ravi", 0],
        2: ["Soma", 1],
        3: ["Mangala", 0],
        4: ["Budha", 1],
        5: ["Guru", 1],
        6: ["Shukra", 1],
        7: ["Shani", 0],
    },
    "Nakshatra": {
        1: ["Ashwini", 0],
        2: ["Bharani", 0],
        3: ["Krittika", 0],
        4: ["Rohini", 1],
        5: ["Mrigashira", 1],
        6: ["Ardra", 0],
        7: ["Punarvasu", 0],
        8: ["Pushya", 1],
        9: ["Ashlesha", 0],
        10: ["Magha", 0],
        11: ["Purva Phalguni", 0],
        12: ["Uttara Phalguni", 1],
        13: ["Hasta", 1],
        14: ["Chitra", 1],
        15: ["Swati", 1],
        16: ["Vishaka", 0],
        17: ["Anurada", 1],
        18: ["Jyeshta", 0],
        19: ["Mula", 0],
        20: ["Purva Ashadha", 0],
        21: ["Uttara Ashadha", 1],
        22: ["Shravana", 0],
        23: ["Dhanishta", 1],
        24: ["Shatabhishak", 1],
        25: ["Purva Bhadrapada", 0],
        26: ["Uttara Bhadrapada", 1],
        27: ["Revati", 1],
    },
    "Yoga": {
        1: ["Vishkambha", 0],
        2: ["Priti", 1],
        3: ["Ayushman", 1],
        4: ["Saubhagya", 1],
        5: ["Sobhana", 1],
        6: ["Atiganda", 0],
        7: ["Sukarma", 1],
        8: ["Dhriti", 1],
        9: ["Soola", 0],
        10: ["Ganda", 0],
        11: ["Vriddha", 0],
        12: ["Dhruva", 1],
        13: ["Vyagatha", 0],
        14: ["Harshana", 1],
        15: ["Vajra", 0],
        16: ["Siddhi", 1],
        17: ["Vyatapata", 0],
        18: ["Variyan", 1],
        19: ["Parigha", 0],
        20: ["Siva", 1],
        21: ["Siddha", 1],
        22: ["Sadhya", 1],
        23: ["Subha", 1],
        24: ["Sukla", 1],
        25: ["Brahma", 1],
        26: ["Indra", 1],
        27: ["Vaidhriti", 0],
    },
    "Karana": {
        1: ["Bava", 1],
        2: ["Balava", 1],
        3: ["Kaulava", 1],
        4: ["Taitila", 1],
        5: ["Gara", 1],
        6: ["Vanija", 0],
        7: ["Vishti", 0],
        8: ["Shakuni", 0],
        9: ["Chatushpat", 0],
        10: ["Naagavan", 0],
        11: ["Kimstugna", 0],
    },
    "Amsha": {
        1: ["Nasta", 0],
        2: ["Vruddhi", 1],
        3: ["Sampattu", 1],
        4: ["Dukkha", 0],
        5: ["Marana", 0],
        6: ["Chorabaya", 0],
        7: ["Santanavruddi", 1],
        8: ["Pashuvruddi", 1],
        9: ["Santhosha", 1],
    },
    "Graha": {
        1: ["Surya", 0],
        2: ["Chandra", 1],
        3: ["Mangala", 0],
        4: ["Budha", 1],
        5: ["Guru", 1],
        6: ["Shukra", 1],
        7: ["Shani", 0],
        8: ["Raahu", 0],
        9: ["Ketu", 0],
    },
    "Dhikpaalaka": {
        1: ["Indra", 1],
        2: ["Agneya", 0],
        3: ["Yama", 0],
        4: ["Niruthi", 0],
        5: ["Varuna", 1],
        6: ["Vayu", 0],
        7: ["Kubera", 1],
        8: ["Eshana", 1],
    },
    "Avasthe": {
        1: ["Balya", 1],
        2: ["Kumaravaste", 1],
        3: ["Youvana", 1],
        4: ["Vardakya", 0],
    },
}